language: go

os: linux
arch: amd64
dist: focal

cache:
  directories:
    - $HOME/.cache/go-build

go:
  - 1.13.x

env:
  global:
    - ENVTEST_ASSETS_DIR=/tmp/testbin
    - SETUP_ENVTEST_SCRIPT_URL=https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/hack/setup-envtest.sh

before_script:
  - mkdir -p $ENVTEST_ASSETS_DIR
  - test -f $ENVTEST_ASSETS_DIR/setup-envtest.sh || curl -sSLo $ENVTEST_ASSETS_DIR/setup-envtest.sh $SETUP_ENVTEST_SCRIPT_URL
  - source $ENVTEST_ASSETS_DIR/setup-envtest.sh
  - fetch_envtest_tools $ENVTEST_ASSETS_DIR
  - setup_envtest_env $ENVTEST_ASSETS_DIR
