# permissions for end users to edit adcasigningrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adcasigningrequest-editor-role
rules:
  - apiGroups:
      - adca.evops.eu
    resources:
      - adcasigningrequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - adca.evops.eu
    resources:
      - adcasigningrequests/status
    verbs:
      - get
