# permissions for end users to edit adcasigninggrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adcasigninggrequest-editor-role
rules:
- apiGroups:
  - adca.evops.eu
  resources:
  - adcasigninggrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - adca.evops.eu
  resources:
  - adcasigninggrequests/status
  verbs:
  - get
