# permissions for end users to view adcasigninggrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adcasigninggrequest-viewer-role
rules:
- apiGroups:
  - adca.evops.eu
  resources:
  - adcasigninggrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - adca.evops.eu
  resources:
  - adcasigninggrequests/status
  verbs:
  - get
