# permissions for end users to view adcasigningrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adcasigningrequest-viewer-role
rules:
  - apiGroups:
      - adca.evops.eu
    resources:
      - adcasigningrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - adca.evops.eu
    resources:
      - adcasigningrequests/status
    verbs:
      - get
